version: '3.8'

services:
  angular-app:
    build:
      context: ./taskify-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./taskify-ui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

  aspnet-api:
    build:
      context: ./taskify-api
      dockerfile: Dockerfile
    ports:
      - "5146:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskifyDev;User Id=sa;Password=GaTo2850;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=GaTo2850
    restart: unless-stopped

